# Metarex.media pihuw theme

# cSpell:ignore docsy fortawesome fontawesome webfonts
title:   "MetaRex"
baseURL: "https://metarex.media"
theme:    pihuw

# override publishing to public so that ko can build a lightweight container
# www-podserver/go.mod module name becomes the image name in docker hub
publishDir: www-podserver/kodata

enableRobotsTXT: true
# ----------------------------------------------------------------------------------------------------------------------
#   __  __          _
#  |  \/  |  __ _  (_)  _ _      _ __    ___   _ _    _  _
#  | |\/| | / _` | | | | ' \    | '  \  / -_) | ' \  | || |
#  |_|  |_| \__,_| |_| |_||_|   |_|_|_| \___| |_||_|  \_,_|
menus:
  main:
    - name: Try
      identifier: tech
    - name: Specifications
      URL: /docs/specifications/
      parent: tech
      weight: 10
    - name: Case Studies
      URL: /docs/studies/
      parent: tech
      weight: 50
      identifier: specs
    - name: MetaRex Register
      URL: /app/reg/
      parent: tech
      weight: 20
      identifier: appreg
    - name: Demos
      URL: /app/demos/
      parent: tech
      weight: 51
      identifier: appdemos
  #                                   _ _     ___
  #   _ __    ___   _ _    _  _     _| | |_  |_  )
  #  | '  \  / -_) | ' \  | || |   |_  .  _|  / /
  #  |_|_|_| \___| |_||_|  \_,_|   |_     _| /___|
  #                                  |_|_|
  menu2:
    - name:  
      URL: https://www.instagram.com/metarex.media?igsh=MWNidHNudDB5MXlwMA==
      identifier: Instagram
      pre: '<i class="instagram icon"></i>'
      post: " 🦖"
      weight: 90
    - name: 
      URL: https://www.linkedin.com/search/results/all/?keywords=%23metarex
      identifier: LinkedIn
      pre: '<i class="linkedin icon"></i>'
      post: " 🦖"
      weight: 100
    - name: 
      URL: https://github.com/orgs/metarex-media/repositories?q=sort%3Aname-asc
      identifier: GitHub
      pre: '<i class="github icon"></i>'
      post: " 🦖"
      weight: 110

    # - name:       See the IBC Winner
    #   URL:        /donate/
    #   identifier: cake
    #   pre:
    #   post:       " 🦖"
    #   weight:     110

# links to linkedin left & right
  
  
  # Menu Rexy
  menurexy:
    - name: MetaRex on Instagram 
      URL: https://www.instagram.com/metarex.media?igsh=MWNidHNudDB5MXlwMA==
      identifier: Instagram
      pre: '<i class="instagram icon"></i>'
      post: " 🦖"
      weight: 90
    - name: MetaRex on LinkedIn
      URL: https://www.linkedin.com/search/results/all/?keywords=%23metarex
      identifier: LinkedIn
      pre: '<i class="linkedin icon"></i>'
      post: " 🦖"
      weight: 100
    - name: MetaRex on GitHub
      URL: https://github.com/orgs/metarex-media/repositories?q=sort%3Aname-asc
      identifier: GitHub
      pre: '<i class="github icon"></i>'
      post: " 🦖"
      weight: 110

    # - name:       See the IBC Winner
    #   URL:        /donate/
    #   identifier: cake
    #   pre:
    #   post:       " 🦖"
    #   weight:     110
    - name: Feed Rexy
      URL: /donate/
      identifier: cake
      pre:
      post: " 🍰"
      weight: 110
    - name: Try a demo
      URL: /app/demos/
      identifier: feed
      pre:  "⏯️ "
      post: " 🦖"
      weight: 120

  footer:
    - name: PiHuW
      identifier: pihuw
      pre: ✏️
      URL: https://github.com/mrmxf/pihuw
    - name: Mr MXF
      identifier: mrmxf
      pre: © 2025
      URL: https://mrmxf.com
    - name: Privacy
      identifier: privacy
      URL: https://mrmxf.com/privacy
    - name: Contact
      pre: ❓
      identifier: contact
      URL: /contact
    - name: About
      identifier: about
      URL: /about


# --- Git ---------------------------------------------------------------------
# Will give values to .Lastmod etc.
enableGitInfo: true

# --- Taxonomies --------------------------------------------------------------
# Comment out to enable taxonomies in pihuw
# --- Taxonomies --------------------------------------------------------------
# Comment out to enable taxonomies in pihuw
# disableKinds: ["taxonomy", "taxonomyTerm"]

# ignore `tmp-` files in /content /data & i*ln
ignoreFiles:
  - \.tmp-$

# You can add your own taxonomies
# See params for how these are shown on pages
# https://gohugo.io/content-management/taxonomies/#what-is-a-taxonomy
taxonomies:
  tag: tags

# --- Permalink --------------------------------------------------------------
# Configure how URLs look like per section.
permalinks:
  blog: "/:section/:year/:month/:day/:slug/"

# --- Image processing --------------------------------------------------------
imaging:
  resampleFilter: CatmullRom
  quality: 75
  anchor: Smart

# --- Services ----------------------------------------------------------------
services:
  googleAnalytics:
    # Comment out the next line to disable GA tracking. Also disables the
    # feature described in [params.ui.feedback].
    #id: UA-00000000-0

# --- Language ----------------------------------------------------------------
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
# Useful when translating.
enableMissingTranslationPlaceholders: false
# Language configuration
languages:
  en:
    title: MetaRex
    label: English
    # Weight used for sorting.
    weight: 1
    params:
      description: Metadata Resource Express

# --- Markdown ----------------------------------------------------------------
#   _ __    __ _   _ _  | |__  _  _   _ __
#  | '  \  / _` | | '_| | / / | || | | '_ \
#  |_|_|_| \__,_| |_|   |_\_\  \_,_| | .__/
#                                    |_|
markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    anchorLineNos: true
    codeFences: true
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    # THIS MUST BE FALSE for mermaid to work!!!
    guessSyntax: false
    # hl_Lines: 
    # See a complete list of available styles at https://gohugo.io/quick-reference/syntax-highlighting-styles/
    # I like light: pastie   dark: monokailight     neutral: hrdark
    style: vs
    lineAnchors: ""
    # hl_Lines:           1
    lineNoStart:        1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2

# --- Output formats ----------------------------------------------------------
# Comment out if you don't want the "print entire section" link enabled.
outputs:
  section:
    - HTML
    - RSS

refLinksErrorLevel: WARNING