# --- Hugo pihuw site.Params are all in this yaml -----------------------------------
copyright:        Mr MXF Ltd
privacy_policy:   https://mrmxf.com/privacy/
contact:          /contact
time_format_blog: 2006-01-02

gdpr:
  owner: Mr MXF Ltd. 
  email: hello@metarex.media

# --- libraries loaded in partial scripts.html -----------------------------------
mermaid:
  enable: true
plantuml:
  enable: false
markmap:
  enable: false
katex:
  enable: false

# --- taxonomy control --------------------------------------------------------
# turn on taxonomies. This allows tags to appear on posts, blogs & articles
# a taxonomy must first be defined in hugo.yaml
taxonomy:
  # set taxonomyCloud: [] to hide taxonomy clouds
  taxonomyCloud:
    - tags
  
  # If used, must have same length as taxonomyCloud
  taxonomyCloudTitle:
    - Tag
    - Category
  # control which tags are shown on pages
  showOnPage:
    - tags


# --- Highlighting -------------------------------------------------------------
pygmentsCodeFences: true
pygmentsUseClasses: false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic: false
#pygmentsOptions: "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle: "tango"

# --- site images --------------------------------------------------------------
# First one is picked as the Twitter card image if not set on page.
images: ["/brand/logo.svg"]

# --- is archived --------------------------------------------------------------
# Flag used to decide whether this is an archived version of the site and so
# display a banner on every page indicating that this is an archived version of
# the docs. Set this flag to "true" if you want to display the banner.
site_is_archived: false

# --- jumbo --------------------------------------------------------------------
# Menu title if your navbar has a jumbo selector to access .Site defined links.
# This menu appears only if you have at least one [params.jumbo] set.
#jumbo_menu_text: Software

#          _   _     _             _
#   __ _  (_) | |_  | |_    _  _  | |__
#  / _` | | | |  _| | ' \  | || | | '_ \
#  \__, | |_|  \__| |_||_|  \_,_| |_.__/
#  |___/
# github information for providing "edit page" or "issues"
github:
  # Account URL for in-page links to opening issues and suggesting changes
  url: https://github.com/metarex-media
  # Repository name for in-page links to opening issues and suggesting changes
  repo: www-metarex-media
  # what branch should the generated site point to e.g. main
  branch: main
  # path to the content folder relative to project root e.g. sample/pihuw-docs/
  contentParent: 
  # If one of your languages is in "/content" (not /content/de) mark it here
  # this is a workaround because a partial cannot read site.DefaultContentLanguageinSubdir
  languageInContentFolder: en

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir: ""

# Uncomment this if your GitHub repo does not have "main" as the default branch,
# or specify a new value if you want to reference another branch in your GitHub links
github_branch: main

# ------------------------------------------------------------------------------
# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id: "d72aa9b2712488cc3"

# Enable Algolia DocSearch
algolia_docsearch: false

# Enable Lunr.js offline search
offlineSearch: false

# ------------------------------------------------------------------------------
# Enable syntax highlighting and copy buttons on code blocks with Prism
prism_syntax_highlighting: true

# --- UI -----------------------------------------------------------------------
ui:
  # hide things that would normally be seen
  hide:
    navbar:
      logo: false
      title: false
      background_cover: false
  #  Set to true to disable breadcrumb navigation.
  breadcrumb_disable: false
  # Set to true to disable the About link in the site footer
  footer_about_disable: true
  # Enable to show the side bar menu in its compact state.
  sidebar_menu_compact: false
  # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
  sidebar_search_disable: true
  # define a partial for a secondary menu e.g. for promos / payments etc.
  navbar2:
    partial: hook/navbar-2      # the name of the partial to render the menu
    menu: menu2                 # the child of menus to supply data
# --- Feedback -----------------------------------------------------------------
# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
feedback:
  enable: true
  # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
  yes: "Glad to hear it! Please <a href='https://github.com/metarex-media/www-metarex-media/issues/new'>tell us how we can improve</a>."
  no: "Sorry to hear that. Please <a href='https://github.com/metarex-media/www-metarex-media/issues/new'>tell us how we can improve</a>."

# --- Reading time -------------------------------------------------------------
# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page,
# add "hide_readingtime: true" to the page's front matter
readingtime:
  enable: true
  # default words per minute when calculating reading time
  wpm:    220

# End user relevant links show up on the footer and community page.
# icon names are here: https://fomantic-ui.com/elements/icon.html
links:
  main:
    - name: Newsletter
      url: /contact
      icon: envelope outline
      desc: Sign up for our newsletter
    - name: Discord
      url: https://discord.gg/uBxZXYZARw
      icon: "discord"
      desc: "Join #metarex.media on Discord to give us your thoughts!"
    - name: Contact
      url: https://contact/
      icon: "envelope"
      desc: "Contact us for more information"
    - name: RSS
      url: https://discord.gg/uBxZXYZARw
      icon: "rss"
      desc: "RSS feed for website updates"
    - name: LinkedIn
      url: https://www.linkedin.com/company/metarex-media/
      icon: "linkedin logo"
    - name: Instagram
      url:  https://www.instagram.com/metarex.media
      icon: "Instagram logo"
  # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
  developer:
    - name: GitHub
      url: https://github.com/metarex-media
      icon: github
      desc: Development takes place here!
    - name: MetaRex Register
      url: https://metarex-media/app/reg
      icon: laptop code
      desc: Browse the metarex regoster

  # Site relevant links. These will show up on right side of footer and in the community page if you have one.
  site:
    - name: Privacy Policy
      url:  https://mrmxf.com/privacy/
      icon: "fab fa-user-shield"
      desc: "metarex.media privacy policy"
    - name: T+C
      url:  https://mrmxf.com/T+C/
      icon: "fab fa-user-shield"
      desc: "mrmxf t+c"

pricelist:
  sections:
  - title: appetiser/small plates
    text: |
      The pièce de resistance, of MetaRex is to be able to download the MetaRex ID (add link) register and have access
      to our instruction manual.
    price: "**_free_**"
  - title: starter
    text: If you want us to validate you document or metadata this is the course for you!
    price: "**£500**"
  - title: Main Course
    text: |
      If you want a custom based service i.e garmin.gpx, this main course is for you
    price: "**£1000 - £5000**"
  - title: Sauce/Source
    text: |
      We want the MetaRex ID register to be open source and free for all. To do our little bit for the world, by making
      the use of metadata run smoother, easier and cheaper for all!

      If you want to own any source code we create for you, we'll have to add a surcharge. 
    price: "**_100% extra_**"
  - title: Dessert
    text:  "Please contact our maître for further details (add contact form)"
    price: "**_POA_**"
  sides:
  - title: Custom
    text: Need a bit more engineering advice? Add this to your order for a catered experience
    price: "**_£1000/day_**"
  - title: Consultancy
    text: For that extra garnish of advice and policy.
    price: "**_£2500_**"
  - title: Artwork
    text: A custom-made piece of artwork/video from our creative team for you to use.
    price: "**_£1000/day_**"
  - title: LinkedIn
    text: Side order of our LinkedIn account (add link)
    price: "**_free_**"
  - title: Instagram
    text: Extra slice of our Instagram (add link) account. Specially designed by our creative team.
    price: "**_free_**"
